// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assembly.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addAssembly = `-- name: AddAssembly :one

INSERT INTO assembly (
    finished_product_batch,
    created_at,
    updated_at,
    assembly_start_date,
    assembly_end_date,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING finished_product_batch, created_at, updated_at, assembly_start_date, assembly_end_date, finished_product_expiry, created_by
`

type AddAssemblyParams struct {
	FinishedProductBatch string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	AssemblyStartDate    time.Time
	AssemblyEndDate      time.Time
	CreatedBy            uuid.UUID
}

func (q *Queries) AddAssembly(ctx context.Context, arg AddAssemblyParams) (Assembly, error) {
	row := q.db.QueryRowContext(ctx, addAssembly,
		arg.FinishedProductBatch,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AssemblyStartDate,
		arg.AssemblyEndDate,
		arg.CreatedBy,
	)
	var i Assembly
	err := row.Scan(
		&i.FinishedProductBatch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssemblyStartDate,
		&i.AssemblyEndDate,
		&i.FinishedProductExpiry,
		&i.CreatedBy,
	)
	return i, err
}

const checkFPBatchExistsInFinishedProduct = `-- name: CheckFPBatchExistsInFinishedProduct :one

SELECT EXISTS (
    SELECT 1
    FROM finished_product
    WHERE finished_product_batch = $1
)
`

func (q *Queries) CheckFPBatchExistsInFinishedProduct(ctx context.Context, finishedProductBatch string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFPBatchExistsInFinishedProduct, finishedProductBatch)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAllAssembly = `-- name: DeleteAllAssembly :exec

DELETE FROM assembly
`

func (q *Queries) DeleteAllAssembly(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAssembly)
	return err
}

const getAssembly = `-- name: GetAssembly :many

SELECT
    finished_product_batch,
    assembly_start_date,
    assembly_end_date,
    finished_product_expiry
FROM assembly
`

type GetAssemblyRow struct {
	FinishedProductBatch  string
	AssemblyStartDate     time.Time
	AssemblyEndDate       time.Time
	FinishedProductExpiry sql.NullTime
}

func (q *Queries) GetAssembly(ctx context.Context) ([]GetAssemblyRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssembly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssemblyRow
	for rows.Next() {
		var i GetAssemblyRow
		if err := rows.Scan(
			&i.FinishedProductBatch,
			&i.AssemblyStartDate,
			&i.AssemblyEndDate,
			&i.FinishedProductExpiry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssemblyByFinishedProductBatch = `-- name: GetAssemblyByFinishedProductBatch :one

SELECT
    finished_product_batch,
    assembly_start_date,
    assembly_end_date,
    finished_product_expiry
FROM assembly
WHERE finished_product_batch = $1
`

type GetAssemblyByFinishedProductBatchRow struct {
	FinishedProductBatch  string
	AssemblyStartDate     time.Time
	AssemblyEndDate       time.Time
	FinishedProductExpiry sql.NullTime
}

func (q *Queries) GetAssemblyByFinishedProductBatch(ctx context.Context, finishedProductBatch string) (GetAssemblyByFinishedProductBatchRow, error) {
	row := q.db.QueryRowContext(ctx, getAssemblyByFinishedProductBatch, finishedProductBatch)
	var i GetAssemblyByFinishedProductBatchRow
	err := row.Scan(
		&i.FinishedProductBatch,
		&i.AssemblyStartDate,
		&i.AssemblyEndDate,
		&i.FinishedProductExpiry,
	)
	return i, err
}

const getAssemblyByIPBatch = `-- name: GetAssemblyByIPBatch :one

SELECT
    a.finished_product_batch,
    fp.In_process_batch_lot,
    a.assembly_start_date,
    a.assembly_end_date,
    a.finished_product_expiry
FROM assembly a
JOIN finished_product fp
    ON a.finished_product_batch = fp.finished_product_batch
WHERE fp.In_process_batch_lot = $1
`

type GetAssemblyByIPBatchRow struct {
	FinishedProductBatch  string
	InProcessBatchLot     string
	AssemblyStartDate     time.Time
	AssemblyEndDate       time.Time
	FinishedProductExpiry sql.NullTime
}

func (q *Queries) GetAssemblyByIPBatch(ctx context.Context, inProcessBatchLot string) (GetAssemblyByIPBatchRow, error) {
	row := q.db.QueryRowContext(ctx, getAssemblyByIPBatch, inProcessBatchLot)
	var i GetAssemblyByIPBatchRow
	err := row.Scan(
		&i.FinishedProductBatch,
		&i.InProcessBatchLot,
		&i.AssemblyStartDate,
		&i.AssemblyEndDate,
		&i.FinishedProductExpiry,
	)
	return i, err
}
