// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch_material_usage.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMaterialUsage = `-- name: AddMaterialUsage :one

INSERT INTO batch_material_usage (
    In_process_batch_lot,
    material_lot,
    created_at,
    updated_at,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING in_process_batch_lot, material_lot, created_at, updated_at, created_by
`

type AddMaterialUsageParams struct {
	InProcessBatchLot string
	MaterialLot       string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CreatedBy         uuid.UUID
}

func (q *Queries) AddMaterialUsage(ctx context.Context, arg AddMaterialUsageParams) (BatchMaterialUsage, error) {
	row := q.db.QueryRowContext(ctx, addMaterialUsage,
		arg.InProcessBatchLot,
		arg.MaterialLot,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
	)
	var i BatchMaterialUsage
	err := row.Scan(
		&i.InProcessBatchLot,
		&i.MaterialLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteAllMaterialUsage = `-- name: DeleteAllMaterialUsage :exec

DELETE FROM batch_material_usage
`

func (q *Queries) DeleteAllMaterialUsage(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMaterialUsage)
	return err
}

const getIPBatchesByMaterialLot = `-- name: GetIPBatchesByMaterialLot :many

SELECT in_process_batch_lot, material_lot, created_at, updated_at, created_by
FROM batch_material_usage
WHERE material_lot = $1
`

func (q *Queries) GetIPBatchesByMaterialLot(ctx context.Context, materialLot string) ([]BatchMaterialUsage, error) {
	rows, err := q.db.QueryContext(ctx, getIPBatchesByMaterialLot, materialLot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchMaterialUsage
	for rows.Next() {
		var i BatchMaterialUsage
		if err := rows.Scan(
			&i.InProcessBatchLot,
			&i.MaterialLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialUsageByIPBatch = `-- name: GetMaterialUsageByIPBatch :many

SELECT in_process_batch_lot, material_lot, created_at, updated_at, created_by
FROM batch_material_usage
WHERE In_process_batch_lot = $1
`

func (q *Queries) GetMaterialUsageByIPBatch(ctx context.Context, inProcessBatchLot string) ([]BatchMaterialUsage, error) {
	rows, err := q.db.QueryContext(ctx, getMaterialUsageByIPBatch, inProcessBatchLot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchMaterialUsage
	for rows.Next() {
		var i BatchMaterialUsage
		if err := rows.Scan(
			&i.InProcessBatchLot,
			&i.MaterialLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialUsageList = `-- name: GetMaterialUsageList :many

SELECT
    In_process_batch_lot,
    material_lot,
    created_at,
    updated_at,
    created_by
FROM batch_material_usage
`

func (q *Queries) GetMaterialUsageList(ctx context.Context) ([]BatchMaterialUsage, error) {
	rows, err := q.db.QueryContext(ctx, getMaterialUsageList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchMaterialUsage
	for rows.Next() {
		var i BatchMaterialUsage
		if err := rows.Scan(
			&i.InProcessBatchLot,
			&i.MaterialLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
