// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blend.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addBlend = `-- name: AddBlend :one
INSERT INTO blend (
    In_process_batch_lot,
    created_at,
    updated_at,
    blend_start_date,
    blend_end_date,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING in_process_batch_lot, created_at, updated_at, blend_start_date, blend_end_date, in_process_blend_hold_end_date, created_by
`

type AddBlendParams struct {
	InProcessBatchLot string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	BlendStartDate    time.Time
	BlendEndDate      time.Time
	CreatedBy         uuid.UUID
}

func (q *Queries) AddBlend(ctx context.Context, arg AddBlendParams) (Blend, error) {
	row := q.db.QueryRowContext(ctx, addBlend,
		arg.InProcessBatchLot,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.BlendStartDate,
		arg.BlendEndDate,
		arg.CreatedBy,
	)
	var i Blend
	err := row.Scan(
		&i.InProcessBatchLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlendStartDate,
		&i.BlendEndDate,
		&i.InProcessBlendHoldEndDate,
		&i.CreatedBy,
	)
	return i, err
}

const checkIPBatchExists = `-- name: CheckIPBatchExists :one
SELECT EXISTS (
    SELECT 1
    FROM batch_material_usage
    WHERE In_process_batch_lot = $1
)
`

func (q *Queries) CheckIPBatchExists(ctx context.Context, inProcessBatchLot string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkIPBatchExists, inProcessBatchLot)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAllBlend = `-- name: DeleteAllBlend :exec
DELETE FROM blend
`

func (q *Queries) DeleteAllBlend(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllBlend)
	return err
}

const deleteIPFromBlend = `-- name: DeleteIPFromBlend :exec
DELETE FROM blend
WHERE In_process_batch_lot = $1
`

func (q *Queries) DeleteIPFromBlend(ctx context.Context, inProcessBatchLot string) error {
	_, err := q.db.ExecContext(ctx, deleteIPFromBlend, inProcessBatchLot)
	return err
}

const getBlendByIPBatch = `-- name: GetBlendByIPBatch :one
SELECT
    In_process_batch_lot,
    created_at,
    updated_at,
    blend_start_date,
    blend_end_date,
    in_process_blend_hold_end_date,
    created_by
FROM blend
WHERE In_process_batch_lot = $1
`

func (q *Queries) GetBlendByIPBatch(ctx context.Context, inProcessBatchLot string) (Blend, error) {
	row := q.db.QueryRowContext(ctx, getBlendByIPBatch, inProcessBatchLot)
	var i Blend
	err := row.Scan(
		&i.InProcessBatchLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlendStartDate,
		&i.BlendEndDate,
		&i.InProcessBlendHoldEndDate,
		&i.CreatedBy,
	)
	return i, err
}

const getBlendList = `-- name: GetBlendList :many
SELECT
    In_process_batch_lot,
    created_at,
    updated_at,
    blend_start_date,
    blend_end_date,
    in_process_blend_hold_end_date,
    created_by
FROM blend
`

func (q *Queries) GetBlendList(ctx context.Context) ([]Blend, error) {
	rows, err := q.db.QueryContext(ctx, getBlendList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blend
	for rows.Next() {
		var i Blend
		if err := rows.Scan(
			&i.InProcessBatchLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlendStartDate,
			&i.BlendEndDate,
			&i.InProcessBlendHoldEndDate,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
