// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fill.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFill = `-- name: AddFill :one
INSERT INTO fill (
    In_process_batch_lot,
    created_at,
    updated_at,
    fill_start_date,
    fill_end_date,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING in_process_batch_lot, created_at, updated_at, fill_start_date, fill_end_date, in_process_disc_hold_end_date, created_by
`

type AddFillParams struct {
	InProcessBatchLot string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	FillStartDate     time.Time
	FillEndDate       time.Time
	CreatedBy         uuid.UUID
}

func (q *Queries) AddFill(ctx context.Context, arg AddFillParams) (Fill, error) {
	row := q.db.QueryRowContext(ctx, addFill,
		arg.InProcessBatchLot,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FillStartDate,
		arg.FillEndDate,
		arg.CreatedBy,
	)
	var i Fill
	err := row.Scan(
		&i.InProcessBatchLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FillStartDate,
		&i.FillEndDate,
		&i.InProcessDiscHoldEndDate,
		&i.CreatedBy,
	)
	return i, err
}

const checkIPBatchExistsInBlend = `-- name: CheckIPBatchExistsInBlend :one
SELECT EXISTS (
    SELECT 1
    FROM blend
    WHERE In_process_batch_lot = $1
)
`

func (q *Queries) CheckIPBatchExistsInBlend(ctx context.Context, inProcessBatchLot string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkIPBatchExistsInBlend, inProcessBatchLot)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAllFill = `-- name: DeleteAllFill :exec
DELETE FROM fill
`

func (q *Queries) DeleteAllFill(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFill)
	return err
}

const getFillByIPBatch = `-- name: GetFillByIPBatch :one
SELECT
    In_process_batch_lot,
    created_at,
    updated_at,
    fill_start_date,
    fill_end_date,
    in_process_disc_hold_end_date,
    created_by
FROM fill
WHERE In_process_batch_lot = $1
`

func (q *Queries) GetFillByIPBatch(ctx context.Context, inProcessBatchLot string) (Fill, error) {
	row := q.db.QueryRowContext(ctx, getFillByIPBatch, inProcessBatchLot)
	var i Fill
	err := row.Scan(
		&i.InProcessBatchLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FillStartDate,
		&i.FillEndDate,
		&i.InProcessDiscHoldEndDate,
		&i.CreatedBy,
	)
	return i, err
}

const getFillList = `-- name: GetFillList :many
SELECT
    In_process_batch_lot,
    created_at,
    updated_at,
    fill_start_date,
    fill_end_date,
    in_process_disc_hold_end_date,
    created_by
FROM fill
`

func (q *Queries) GetFillList(ctx context.Context) ([]Fill, error) {
	rows, err := q.db.QueryContext(ctx, getFillList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fill
	for rows.Next() {
		var i Fill
		if err := rows.Scan(
			&i.InProcessBatchLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FillStartDate,
			&i.FillEndDate,
			&i.InProcessDiscHoldEndDate,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
