// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finished_product.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFinishedProduct = `-- name: AddFinishedProduct :one

INSERT INTO finished_product (
    finished_product_batch,
    In_process_batch_lot,
    component_1_batch,
    component_2_batch,
    created_at,
    updated_at,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING finished_product_batch, in_process_batch_lot, component_1_batch, component_2_batch, created_at, updated_at, created_by
`

type AddFinishedProductParams struct {
	FinishedProductBatch string
	InProcessBatchLot    string
	Component1Batch      string
	Component2Batch      string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedBy            uuid.UUID
}

func (q *Queries) AddFinishedProduct(ctx context.Context, arg AddFinishedProductParams) (FinishedProduct, error) {
	row := q.db.QueryRowContext(ctx, addFinishedProduct,
		arg.FinishedProductBatch,
		arg.InProcessBatchLot,
		arg.Component1Batch,
		arg.Component2Batch,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
	)
	var i FinishedProduct
	err := row.Scan(
		&i.FinishedProductBatch,
		&i.InProcessBatchLot,
		&i.Component1Batch,
		&i.Component2Batch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const checkFPBatchExistsInAssembly = `-- name: CheckFPBatchExistsInAssembly :one

SELECT EXISTS (
    SELECT 1
    FROM assembly
    WHERE finished_product_batch = $1
)
`

func (q *Queries) CheckFPBatchExistsInAssembly(ctx context.Context, finishedProductBatch string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFPBatchExistsInAssembly, finishedProductBatch)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkIPBatchExistsInFill = `-- name: CheckIPBatchExistsInFill :one

SELECT EXISTS (
    SELECT 1
    FROM fill
    WHERE In_process_batch_lot = $1
)
`

func (q *Queries) CheckIPBatchExistsInFill(ctx context.Context, inProcessBatchLot string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkIPBatchExistsInFill, inProcessBatchLot)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countFinishedProducts = `-- name: CountFinishedProducts :one

SELECT COUNT(*)
FROM finished_product
`

func (q *Queries) CountFinishedProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFinishedProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllFinishedProducts = `-- name: DeleteAllFinishedProducts :exec

DELETE FROM finished_product
`

func (q *Queries) DeleteAllFinishedProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFinishedProducts)
	return err
}

const deleteLotFromFinishedProducts = `-- name: DeleteLotFromFinishedProducts :exec

DELETE FROM finished_product
WHERE finished_product_batch = $1
`

func (q *Queries) DeleteLotFromFinishedProducts(ctx context.Context, finishedProductBatch string) error {
	_, err := q.db.ExecContext(ctx, deleteLotFromFinishedProducts, finishedProductBatch)
	return err
}

const getFinishedProduct = `-- name: GetFinishedProduct :many

SELECT
    finished_product_batch,
    In_process_batch_lot,
    component_1_batch,
    component_2_batch
FROM finished_product
`

type GetFinishedProductRow struct {
	FinishedProductBatch string
	InProcessBatchLot    string
	Component1Batch      string
	Component2Batch      string
}

func (q *Queries) GetFinishedProduct(ctx context.Context) ([]GetFinishedProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getFinishedProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFinishedProductRow
	for rows.Next() {
		var i GetFinishedProductRow
		if err := rows.Scan(
			&i.FinishedProductBatch,
			&i.InProcessBatchLot,
			&i.Component1Batch,
			&i.Component2Batch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinishedProductByFinishedProductBatch = `-- name: GetFinishedProductByFinishedProductBatch :one

SELECT
    finished_product_batch,
    In_process_batch_lot,
    component_1_batch,
    component_2_batch
FROM finished_product
WHERE finished_product_batch = $1
`

type GetFinishedProductByFinishedProductBatchRow struct {
	FinishedProductBatch string
	InProcessBatchLot    string
	Component1Batch      string
	Component2Batch      string
}

func (q *Queries) GetFinishedProductByFinishedProductBatch(ctx context.Context, finishedProductBatch string) (GetFinishedProductByFinishedProductBatchRow, error) {
	row := q.db.QueryRowContext(ctx, getFinishedProductByFinishedProductBatch, finishedProductBatch)
	var i GetFinishedProductByFinishedProductBatchRow
	err := row.Scan(
		&i.FinishedProductBatch,
		&i.InProcessBatchLot,
		&i.Component1Batch,
		&i.Component2Batch,
	)
	return i, err
}

const getFinishedProductByIPBatch = `-- name: GetFinishedProductByIPBatch :one

SELECT
    finished_product_batch,
    In_process_batch_lot,
    component_1_batch,
    component_2_batch
FROM finished_product
WHERE In_process_batch_lot = $1
`

type GetFinishedProductByIPBatchRow struct {
	FinishedProductBatch string
	InProcessBatchLot    string
	Component1Batch      string
	Component2Batch      string
}

func (q *Queries) GetFinishedProductByIPBatch(ctx context.Context, inProcessBatchLot string) (GetFinishedProductByIPBatchRow, error) {
	row := q.db.QueryRowContext(ctx, getFinishedProductByIPBatch, inProcessBatchLot)
	var i GetFinishedProductByIPBatchRow
	err := row.Scan(
		&i.FinishedProductBatch,
		&i.InProcessBatchLot,
		&i.Component1Batch,
		&i.Component2Batch,
	)
	return i, err
}
