// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRawMaterial = `-- name: AddRawMaterial :one
INSERT INTO materials (material_lot, created_at, updated_at, material_type, mfg_date, exp_date, created_by)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING material_lot, created_at, updated_at, material_type, mfg_date, exp_date, created_by
`

type AddRawMaterialParams struct {
	MaterialLot  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	MaterialType string
	MfgDate      time.Time
	ExpDate      time.Time
	CreatedBy    uuid.UUID
}

func (q *Queries) AddRawMaterial(ctx context.Context, arg AddRawMaterialParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, addRawMaterial,
		arg.MaterialLot,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MaterialType,
		arg.MfgDate,
		arg.ExpDate,
		arg.CreatedBy,
	)
	var i Material
	err := row.Scan(
		&i.MaterialLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialType,
		&i.MfgDate,
		&i.ExpDate,
		&i.CreatedBy,
	)
	return i, err
}

const deleteMaterials = `-- name: DeleteMaterials :exec
DELETE FROM materials
`

func (q *Queries) DeleteMaterials(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMaterials)
	return err
}

const getRawMaterialByLot = `-- name: GetRawMaterialByLot :one
SELECT material_lot, created_at, updated_at, material_type, mfg_date, exp_date, created_by
FROM materials
WHERE material_lot = $1
`

func (q *Queries) GetRawMaterialByLot(ctx context.Context, materialLot string) (Material, error) {
	row := q.db.QueryRowContext(ctx, getRawMaterialByLot, materialLot)
	var i Material
	err := row.Scan(
		&i.MaterialLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialType,
		&i.MfgDate,
		&i.ExpDate,
		&i.CreatedBy,
	)
	return i, err
}

const getRawMaterials = `-- name: GetRawMaterials :many
SELECT material_lot, created_at, updated_at, material_type, mfg_date, exp_date, created_by
FROM materials
`

func (q *Queries) GetRawMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, getRawMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.MaterialLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaterialType,
			&i.MfgDate,
			&i.ExpDate,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
