// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Assembly struct {
	InProcessBatchLot     uuid.UUID
	FinishedProductBatch  uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	AssemblyStartDate     time.Time
	AssemblyEndDate       time.Time
	FinishedProductExpiry sql.NullTime
	CreatedBy             uuid.UUID
}

type BatchMaterialUsage struct {
	InProcessBatchLot uuid.UUID
	MaterialLot       string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CreatedBy         uuid.UUID
}

type Blend struct {
	InProcessBatchLot         uuid.UUID
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	BlendStartDate            time.Time
	BlendEndDate              time.Time
	InProcessBlendHoldEndDate sql.NullTime
	CreatedBy                 uuid.UUID
}

type Fill struct {
	InProcessBatchLot        uuid.UUID
	CreatedAt                time.Time
	UpdatedAt                time.Time
	FillStartDate            time.Time
	FillEndDate              time.Time
	InProcessDiscHoldEndDate sql.NullTime
	CreatedBy                uuid.UUID
}

type IpcQcResult struct {
	InProcessBatchLot uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	TestName          string
	Replicate         int32
	TestDate          time.Time
	Result            sql.NullString
	CreatedBy         uuid.UUID
}

type Material struct {
	MaterialLot  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	MaterialType string
	MfgDate      time.Time
	ExpDate      time.Time
	CreatedBy    uuid.UUID
}

type QcRelease struct {
	FinishedProductBatch uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TestName             string
	Replicate            int32
	TestDate             time.Time
	Result               sql.NullString
	CreatedBy            uuid.UUID
}

type Spec struct {
	TestName  string
	CreatedAt time.Time
	UpdatedAt time.Time
	MinResult sql.NullString
	MaxResult sql.NullString
	RsdLimit  sql.NullString
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}
