// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qc_release.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addQCReleaseResults = `-- name: AddQCReleaseResults :one

INSERT INTO qc_release (
    finished_product_batch,
    created_at,
    updated_at,
    test_name,
    replicate,
    test_date,
    result,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING finished_product_batch, created_at, updated_at, test_name, replicate, test_date, result, created_by
`

type AddQCReleaseResultsParams struct {
	FinishedProductBatch string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TestName             string
	Replicate            int32
	TestDate             time.Time
	Result               sql.NullString
	CreatedBy            uuid.UUID
}

func (q *Queries) AddQCReleaseResults(ctx context.Context, arg AddQCReleaseResultsParams) (QcRelease, error) {
	row := q.db.QueryRowContext(ctx, addQCReleaseResults,
		arg.FinishedProductBatch,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TestName,
		arg.Replicate,
		arg.TestDate,
		arg.Result,
		arg.CreatedBy,
	)
	var i QcRelease
	err := row.Scan(
		&i.FinishedProductBatch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TestName,
		&i.Replicate,
		&i.TestDate,
		&i.Result,
		&i.CreatedBy,
	)
	return i, err
}

const checkFPBatchExists = `-- name: CheckFPBatchExists :one

SELECT EXISTS (
    SELECT 1
    FROM assembly
    WHERE finished_product_batch = $1
)
`

func (q *Queries) CheckFPBatchExists(ctx context.Context, finishedProductBatch string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFPBatchExists, finishedProductBatch)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkFPBatchExistsInQCRelease = `-- name: CheckFPBatchExistsInQCRelease :one
SELECT EXISTS (
    SELECT 1
    FROM qc_release
    WHERE finished_product_batch = $1
)
`

func (q *Queries) CheckFPBatchExistsInQCRelease(ctx context.Context, finishedProductBatch string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkFPBatchExistsInQCRelease, finishedProductBatch)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countQCReleaseResults = `-- name: CountQCReleaseResults :one
SELECT COUNT(*)
FROM qc_release
WHERE finished_product_batch = $1
AND test_name = $2
`

type CountQCReleaseResultsParams struct {
	FinishedProductBatch string
	TestName             string
}

func (q *Queries) CountQCReleaseResults(ctx context.Context, arg CountQCReleaseResultsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQCReleaseResults, arg.FinishedProductBatch, arg.TestName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllQCReleaseResults = `-- name: DeleteAllQCReleaseResults :exec

DELETE FROM qc_release
`

func (q *Queries) DeleteAllQCReleaseResults(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllQCReleaseResults)
	return err
}

const deleteQCReleaseResultsForFPBatch = `-- name: DeleteQCReleaseResultsForFPBatch :exec

DELETE FROM qc_release
WHERE finished_product_batch = $1
`

func (q *Queries) DeleteQCReleaseResultsForFPBatch(ctx context.Context, finishedProductBatch string) error {
	_, err := q.db.ExecContext(ctx, deleteQCReleaseResultsForFPBatch, finishedProductBatch)
	return err
}

const getAllQCReleaseResults = `-- name: GetAllQCReleaseResults :many

SELECT
    finished_product_batch,
    created_at,
    updated_at,
    test_name,
    replicate,
    test_date,
    result
FROM qc_release
`

type GetAllQCReleaseResultsRow struct {
	FinishedProductBatch string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TestName             string
	Replicate            int32
	TestDate             time.Time
	Result               sql.NullString
}

func (q *Queries) GetAllQCReleaseResults(ctx context.Context) ([]GetAllQCReleaseResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllQCReleaseResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllQCReleaseResultsRow
	for rows.Next() {
		var i GetAllQCReleaseResultsRow
		if err := rows.Scan(
			&i.FinishedProductBatch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TestName,
			&i.Replicate,
			&i.TestDate,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQCReleaseResultsByFPBatch = `-- name: GetQCReleaseResultsByFPBatch :many

SELECT
    finished_product_batch,
    created_at,
    updated_at,
    test_name,
    replicate,
    test_date,
    result
FROM qc_release
WHERE finished_product_batch = $1
`

type GetQCReleaseResultsByFPBatchRow struct {
	FinishedProductBatch string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TestName             string
	Replicate            int32
	TestDate             time.Time
	Result               sql.NullString
}

func (q *Queries) GetQCReleaseResultsByFPBatch(ctx context.Context, finishedProductBatch string) ([]GetQCReleaseResultsByFPBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, getQCReleaseResultsByFPBatch, finishedProductBatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQCReleaseResultsByFPBatchRow
	for rows.Next() {
		var i GetQCReleaseResultsByFPBatchRow
		if err := rows.Scan(
			&i.FinishedProductBatch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TestName,
			&i.Replicate,
			&i.TestDate,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQCReleaseResultsByIPBatch = `-- name: GetQCReleaseResultsByIPBatch :many

SELECT
    qr.finished_product_batch,
    fp.In_process_batch_lot,
    qr.test_name,
    qr.replicate,
    qr.test_date,
    qr.result
FROM qc_release qr
JOIN finished_product fp
    ON fp.finished_product_batch = qr.finished_product_batch
WHERE fp.In_process_batch_lot = $1
`

type GetQCReleaseResultsByIPBatchRow struct {
	FinishedProductBatch string
	InProcessBatchLot    string
	TestName             string
	Replicate            int32
	TestDate             time.Time
	Result               sql.NullString
}

func (q *Queries) GetQCReleaseResultsByIPBatch(ctx context.Context, inProcessBatchLot string) ([]GetQCReleaseResultsByIPBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, getQCReleaseResultsByIPBatch, inProcessBatchLot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQCReleaseResultsByIPBatchRow
	for rows.Next() {
		var i GetQCReleaseResultsByIPBatchRow
		if err := rows.Scan(
			&i.FinishedProductBatch,
			&i.InProcessBatchLot,
			&i.TestName,
			&i.Replicate,
			&i.TestDate,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
