// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw_material.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRawMaterial = `-- name: AddRawMaterial :one
INSERT INTO materials (material_lot, created_at, updated_at, material_type, mfg_date, exp_date)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING material_lot, created_at, updated_at, material_type, mfg_date, exp_date
`

type AddRawMaterialParams struct {
	MaterialLot  uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	MaterialType string
	MfgDate      time.Time
	ExpDate      time.Time
}

func (q *Queries) AddRawMaterial(ctx context.Context, arg AddRawMaterialParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, addRawMaterial,
		arg.MaterialLot,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MaterialType,
		arg.MfgDate,
		arg.ExpDate,
	)
	var i Material
	err := row.Scan(
		&i.MaterialLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialType,
		&i.MfgDate,
		&i.ExpDate,
	)
	return i, err
}

const getRawMaterialByLot = `-- name: GetRawMaterialByLot :one
SELECT material_lot, created_at, updated_at, material_type, mfg_date, exp_date
FROM materials
WHERE material_lot = $1
`

func (q *Queries) GetRawMaterialByLot(ctx context.Context, materialLot uuid.UUID) (Material, error) {
	row := q.db.QueryRowContext(ctx, getRawMaterialByLot, materialLot)
	var i Material
	err := row.Scan(
		&i.MaterialLot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaterialType,
		&i.MfgDate,
		&i.ExpDate,
	)
	return i, err
}

const getRawMaterials = `-- name: GetRawMaterials :many
SELECT material_lot, created_at, updated_at, material_type, mfg_date, exp_date
FROM materials
`

func (q *Queries) GetRawMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, getRawMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.MaterialLot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaterialType,
			&i.MfgDate,
			&i.ExpDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
