// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addSpecs = `-- name: AddSpecs :one

INSERT INTO specs (
    test_name,
    created_at,
    updated_at,
    min_result,
    max_result,
    mean_min,
    mean_max,
    rsd_limit,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING test_name, created_at, updated_at, min_result, max_result, rsd_limit, created_by, mean_min, mean_max
`

type AddSpecsParams struct {
	TestName  string
	CreatedAt time.Time
	UpdatedAt time.Time
	MinResult sql.NullString
	MaxResult sql.NullString
	MeanMin   sql.NullString
	MeanMax   sql.NullString
	RsdLimit  sql.NullString
	CreatedBy uuid.UUID
}

func (q *Queries) AddSpecs(ctx context.Context, arg AddSpecsParams) (Spec, error) {
	row := q.db.QueryRowContext(ctx, addSpecs,
		arg.TestName,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MinResult,
		arg.MaxResult,
		arg.MeanMin,
		arg.MeanMax,
		arg.RsdLimit,
		arg.CreatedBy,
	)
	var i Spec
	err := row.Scan(
		&i.TestName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinResult,
		&i.MaxResult,
		&i.RsdLimit,
		&i.CreatedBy,
		&i.MeanMin,
		&i.MeanMax,
	)
	return i, err
}

const deleteAllSpecs = `-- name: DeleteAllSpecs :exec
DELETE FROM specs
`

func (q *Queries) DeleteAllSpecs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSpecs)
	return err
}

const getSpecs = `-- name: GetSpecs :many

SELECT
    test_name,
    created_at,
    updated_at,
    min_result,
    max_result,
    mean_min,
    mean_max,
    rsd_limit,
    created_by
FROM specs
`

type GetSpecsRow struct {
	TestName  string
	CreatedAt time.Time
	UpdatedAt time.Time
	MinResult sql.NullString
	MaxResult sql.NullString
	MeanMin   sql.NullString
	MeanMax   sql.NullString
	RsdLimit  sql.NullString
	CreatedBy uuid.UUID
}

func (q *Queries) GetSpecs(ctx context.Context) ([]GetSpecsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpecsRow
	for rows.Next() {
		var i GetSpecsRow
		if err := rows.Scan(
			&i.TestName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MinResult,
			&i.MaxResult,
			&i.MeanMin,
			&i.MeanMax,
			&i.RsdLimit,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecsByTestName = `-- name: GetSpecsByTestName :one

SELECT
    test_name,
    created_at,
    updated_at,
    min_result,
    max_result,
    mean_min,
    mean_max,
    rsd_limit,
    created_by
FROM specs
WHERE test_name = $1
`

type GetSpecsByTestNameRow struct {
	TestName  string
	CreatedAt time.Time
	UpdatedAt time.Time
	MinResult sql.NullString
	MaxResult sql.NullString
	MeanMin   sql.NullString
	MeanMax   sql.NullString
	RsdLimit  sql.NullString
	CreatedBy uuid.UUID
}

func (q *Queries) GetSpecsByTestName(ctx context.Context, testName string) (GetSpecsByTestNameRow, error) {
	row := q.db.QueryRowContext(ctx, getSpecsByTestName, testName)
	var i GetSpecsByTestNameRow
	err := row.Scan(
		&i.TestName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinResult,
		&i.MaxResult,
		&i.MeanMin,
		&i.MeanMax,
		&i.RsdLimit,
		&i.CreatedBy,
	)
	return i, err
}
